name: btab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-162.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  model_viewer_plus: ^1.9.3
  just_audio: ^0.10.5
  http: ^1.6.0
  video_player: ^2.10.1
  flutter_html: ^3.0.0
  flutter_html_all: ^3.0.0
  flutter_html_audio: ^3.0.0
  flutter_html_iframe: ^3.0.0
  flutter_html_math: ^3.0.0
  flutter_html_svg: ^3.0.0
  flutter_html_table: ^3.0.0
  flutter_html_video: ^3.0.0
  flutter_bloc: ^9.1.1
  flutter_math_fork: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/
  fonts:
     - family: Tinos
       fonts:
         - asset: assets/fonts/Tinos-Regular.ttf
